import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {validateMapImage,validateMapService} from './wms-client.js';
const id='735f227b-5f95-473f-967b-077f3419bc68',sha='a'.repeat(64);
function image(){const root='https://imagery.nationalmap.gov/arcgis/rest/services/USGSNAIPImagery/ImageServer',metadata=readFileSync(new URL('../../crates/geod-runtime/fixtures/arcgis-map/usgs-metadata.json',import.meta.url),'utf8'),v=JSON.parse(metadata),url='https://imagery.nationalmap.gov/arcgis/rest/directories/imagery_output/USGSNAIPImagery_ImageServer/_ags_image.png',requested=[-122.52,37.72,-122.40,37.80],bounds=[-122.52,37.70,-122.40,37.82];
 const caps={serviceType:'ImageServer',metadata,layersMetadata:null,excludedLayers:[]};
 const s={id,name:'USGS',url:root,title:v.name,version:String(v.currentVersion),mapUrl:root+'/exportImage',maxWidth:2048,maxHeight:2048,capabilitiesSha256:sha,connectedAt:'2026-10-03T00:00:00Z',accessConstraints:'',layers:[{name:'image',title:v.name,crs:'EPSG:4326',styles:[],time:null}],arcgis:caps};
 const u=new URL(s.mapUrl);for(const [k,v]of Object.entries({f:'json',_geodRequest:id,bbox:requested.join(','),bboxSR:'4326',imageSR:'4326',size:'256,256',format:'png32',transparent:'true',adjustAspectRatio:'true'}))u.searchParams.set(k,v);
 const raw=JSON.stringify({href:url,width:256,height:256,extent:{xmin:bounds[0],ymin:bounds[1],xmax:bounds[2],ymax:bounds[3],spatialReference:{wkid:4326,latestWkid:4326}}});
 return {service:s,id,name:'NAIP · ArcGIS',width:256,height:256,bounds,bytes:1000,sha256:sha,crs:'EPSG:4326',source:{serviceUrl:root,serviceName:s.name,serviceTitle:s.title,version:s.version,mapEndpoint:s.mapUrl,capabilitiesSha256:sha,layerName:'image',layerTitle:v.name,style:'',time:null,requestCrs:'EPSG:4326',requestUrl:u.href,requestedAt:s.connectedAt,selection:'bbox-rendered-map',arcgis:{capabilities:caps,requestedBounds:requested,requestId:id,exportMetadata:raw,exportSha256:sha,imageUrl:url}}};}
test('ArcGIS service and image use the common map validators with actual returned extent',()=>{const a=image();validateMapService(a.service);delete a.service;assert.equal(validateMapImage(a),a);assert.notDeepEqual(a.bounds,a.source.arcgis.requestedBounds);});
test('ArcGIS request, href and export extent cannot silently diverge',()=>{for(const mutate of [a=>{a.bounds=a.source.arcgis.requestedBounds;},a=>{a.source.requestUrl+='&token=secret';},a=>{a.source.arcgis.imageUrl='https://evil.example.com/_ags_image.png';},a=>{a.source.wmts={};},a=>{a.source.arcgis.requestedBounds=[-123,37,-122,38];},a=>{const e=JSON.parse(a.source.arcgis.exportMetadata);e.extent.spatialReference.latestWkid=3857;a.source.arcgis.exportMetadata=JSON.stringify(e);}]){const a=image();mutate(a);assert.throws(()=>validateMapImage(a));}});
test('ArcGIS rejects service exceptions and mixed discovery protocols',()=>{const a=image();a.source.arcgis.exportMetadata='{"error":{"code":499}}';assert.throws(()=>validateMapImage(a));const b=image();b.service.wmts={};assert.throws(()=>validateMapService(b.service));});
