import React,{useEffect,useState} from 'react';
import {Plug,Plus,RefreshCw,Trash2,Download,MapPin} from 'lucide-react';
import {Modal,Button,Input,Select,Spinner,Disclosure} from './ui/index.jsx';
import {featureRequest,validQueryBounds,validOverpassBounds} from './features-client.js';
import {useI18n} from './i18n.jsx';
import './features.css';
export function FeatureServiceDialog({areaBounds,areaPolygon,onClose,onImported}) {
  const {t,number}=useI18n();
  const [services,setServices]=useState([]),[serviceId,setServiceId]=useState(''),[collectionId,setCollectionId]=useState('');
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[adding,setAdding]=useState(false);
  const [name,setName]=useState(''),[url,setUrl]=useState(''),[protocol,setProtocol]=useState('OGC'),[search,setSearch]=useState(''),[responseFormat,setResponseFormat]=useState('');
  useEffect(()=>{const abort=new AbortController();featureRequest('list',{},abort.signal).then(list=>{setServices(list);setServiceId(list[0]?.id||'');setAdding(!list.length);}).catch(e=>{if(!abort.signal.aborted){setError(e.message);setAdding(true);}}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[]);
  const selected=services.find(s=>s.id===serviceId);
  const collectionLabel=c=>selected?.overpass?t(c.title):c.title;
  const filtered=(selected?.collections||[]).filter(c=>`${collectionLabel(c)} ${c.id}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  const collection=selected?.collections.find(c=>c.id===collectionId);
  const wfsFormat=collection?.wfs?.formats.find(f=>f.id===responseFormat);
  useEffect(()=>{setCollectionId(selected?.collections[0]?.id||'');setSearch('');},[serviceId,selected]);
  useEffect(()=>{setResponseFormat(collection?.wfs?.defaultFormat||'');},[collection]);
  const run=async (kind,action)=>{setBusy(kind);setError('');try{await action();}catch(e){setError(e.message);}finally{setBusy('');}};
  const connect=()=>run('connect',async()=>{const saved=await featureRequest('connect',{name,url,...(protocol!=='OGC'?{protocol}: {})});setServices(list=>[...list.filter(s=>s.id!==saved.id),saved]);setServiceId(saved.id);setAdding(false);});
  const remove=()=>run('remove',async()=>{await featureRequest('forget',{id:serviceId});const rest=services.filter(s=>s.id!==serviceId);setServices(rest);setServiceId(rest[0]?.id||'');setAdding(!rest.length);});
  const query=()=>run('query',async()=>{const file=await featureRequest('query',{serviceId,collectionId,bounds:areaBounds,areaGeometry:areaPolygon?.geometry||null,...(selected?.wfs?{responseFormat}:{})});onImported(file);onClose();});
  return <Modal title={t('Get vector data')} description={t('Connect a vector data service and save matching features locally.')} onClose={onClose} closeDisabled={Boolean(busy)} closeLabel={t('Close')} className="feature-service-dialog">
    {loading?<div className="feature-loading"><Spinner/>{t('Loading data services')}</div>:<div className="feature-service-body">
      {!adding&&<div className="feature-service-row"><label className="feature-field"><span>{t('Data service')}</span><Select aria-label={t('Data service')} value={serviceId} disabled={Boolean(busy)} onChange={e=>setServiceId(e.target.value)}>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></label>
        <div className="feature-service-icons"><Button size="icon" variant="secondary" aria-label={t('Add data service')} tooltip={t('Add data service')} disabled={Boolean(busy)} onClick={()=>setAdding(true)}><Plus size={16}/></Button>
          <Button size="icon" variant="secondary" aria-label={t('Refresh service collections')} tooltip={t('Refresh service collections')} disabled={!selected||Boolean(busy)} onClick={()=>run('connect',async()=>{const saved=await featureRequest('connect',{name:selected.name,url:selected.url,...(selected.arcgis?{protocol:'ArcGIS'}:selected.overpass?{protocol:'Overpass'}:selected.wfs?{protocol:'WFS2'}:{})});setServices(list=>list.map(s=>s.id===saved.id?saved:s));})}><RefreshCw size={16}/></Button>
          <Button size="icon" variant="quiet" aria-label={t('Remove service connection')} tooltip={t('Remove service connection')} disabled={!selected||Boolean(busy)} onClick={remove}><Trash2 size={16}/></Button></div></div>}
      {adding&&<section className="feature-connect"><label className="feature-field"><span>{t('Service protocol')}</span><Select aria-label={t('Service protocol')} value={protocol} disabled={Boolean(busy)} onChange={e=>{setProtocol(e.target.value);if(['Overpass','WFS2'].includes(e.target.value))setUrl('');}}><option value="OGC">OGC API Features</option><option value="ArcGIS">ArcGIS Feature Service</option><option value="Overpass">OSM Overpass</option><option value="WFS2">WFS 2.0</option></Select></label>
        <label className="feature-field"><span>{t('Connection name')}</span><Input aria-label={t('Connection name')} maxLength={80} value={name} disabled={Boolean(busy)} onChange={e=>setName(e.target.value)}/></label>
        <label className="feature-field"><span>{t(protocol==='Overpass'?'Overpass endpoint URL':protocol==='WFS2'?'WFS service URL':'Service landing URL')}</span><Input aria-label={t(protocol==='Overpass'?'Overpass endpoint URL':protocol==='WFS2'?'WFS service URL':'Service landing URL')} placeholder="https://…" value={url} maxLength={2048} disabled={Boolean(busy)} onChange={e=>setUrl(e.target.value)}/></label>
        {protocol==='Overpass'&&<p className="feature-help">{t('Use an Overpass endpoint you operate or are authorized to use with this application. No public endpoint is selected automatically.')}</p>}
        {protocol==='WFS2'&&<p className="feature-help">{t('Enter a WFS 2.0 service endpoint. Available feature types and response formats are discovered after connecting.')}</p>}
        <div className="feature-connect-actions"><Button icon={Plug} primary disabled={Boolean(busy)||!name.trim()||!url.trim()} onClick={connect}>{t('Connect service')}</Button>{['OGC','ArcGIS'].includes(protocol)&&<><Button variant="quiet" disabled={Boolean(busy)} onClick={()=>{setProtocol('OGC');setName('pygeoapi · Natural Earth');setUrl('https://demo.pygeoapi.io/stable');}}>{t('Use public demo')}</Button><Button variant="quiet" disabled={Boolean(busy)} onClick={()=>{setProtocol('ArcGIS');setName('Esri · Earthquakes since 1970');setUrl('https://sampleserver6.arcgisonline.com/arcgis/rest/services/Earthquakes_Since1970/FeatureServer');}}>{t('Use ArcGIS demo')}</Button></>}{services.length>0&&<Button variant="quiet" disabled={Boolean(busy)} onClick={()=>setAdding(false)}>{t('Cancel')}</Button>}</div>
        <p className="feature-help">{t(protocol==='WFS2'?'Use a public HTTPS endpoint or WFS 2.0 GetCapabilities URL without credentials. Uses the proxy selected in Settings.':protocol==='Overpass'?'Use a public HTTPS URL without credentials or query parameters. Uses the proxy selected in Settings.':'Public HTTPS services only. Uses the proxy selected in Settings. The demo service is for testing and may be unavailable.')}</p></section>}
      {!adding&&selected&&<>
        <label className="feature-field"><span>{t('Collection')}</span><Input type="search" aria-label={t('Find a collection')} placeholder={t('Find a collection')} value={search} disabled={Boolean(busy)} onChange={e=>setSearch(e.target.value)}/><Select aria-label={t('Collection')} value={filtered.some(c=>c.id===collectionId)?collectionId:''} disabled={!filtered.length||Boolean(busy)} onChange={e=>setCollectionId(e.target.value)}><option value="">{t('Choose a collection')}</option>{filtered.map(c=><option key={c.id} value={c.id}>{collectionLabel(c)}</option>)}</Select></label>
        {collection?.wfs&&<label className="feature-field"><span>{t('Service response format')}</span><Select aria-label={t('Service response format')} value={responseFormat} disabled={Boolean(busy)} onChange={e=>setResponseFormat(e.target.value)}>{collection.wfs.formats.map(format=><option key={format.id} value={format.id}>{format.id==='gml32'?'GML 3.2':'GeoJSON'}</option>)}</Select><small className="feature-help">{t(responseFormat==='gml32'?'The service returns GML 3.2. GeoD converts it locally to WGS84 GeoJSON and preserves the original responses.':'The service returns GeoJSON. GeoD verifies it and preserves the original responses.')}</small></label>}
        {!selected.collections.length&&<p className="feature-help">{t(selected.wfs?'This service has no supported WFS feature types.':'This service has no supported GeoJSON feature collections.')}</p>}
        {collection&&<div className="feature-collection-summary">{selected.wfs&&collection.description.length>280?<Disclosure summary={t('Collection description')}><p className="feature-description">{collection.description}</p></Disclosure>:<p>{selected.overpass?t(collection.description):collection.description}</p>}<Disclosure summary={t('Collection source and license')}><dl className="vector-properties"><dt>{t('Service protocol')}</dt><dd>{selected.arcgis?'ArcGIS Feature Service':selected.overpass?'OSM Overpass':selected.wfs?'WFS 2.0':'OGC API Features'}</dd><dt>{t('Data service')}</dt><dd>{selected.url}</dd><dt>{t('Collection identifier')}</dt><dd>{collection.id}</dd>{collection.arcgis&&<ArcgisLayerDetails layer={collection.arcgis} copyright={collection.arcgis.copyrightText||selected.arcgis.copyrightText}/>} {collection.wfs&&<><dt>{t('Feature namespace')}</dt><dd>{collection.wfs.namespace}</dd><dt>{t('Declared default CRS')}</dt><dd>{collection.wfs.defaultCrs}</dd><WfsServiceDetails source={selected.wfs}/></>}{selected.overpass&&<><dt>{t('Service software')}</dt><dd>{selected.overpass.generator} · API {selected.overpass.apiVersion}</dd><dt>{t('Service metadata SHA-256')}</dt><dd>{selected.overpass.metadataSha256}</dd><dt>{t('Copyright notice')}</dt><dd>{selected.overpass.copyrightText}</dd></>}<dt>{t('License')}</dt><dd>{collection.licenseLinks.length?collection.licenseLinks.join('\n'):t('No dataset license link declared; check collection metadata before reuse.')}</dd></dl></Disclosure></div>}
        {selected.arcgis?.excludedLayers.length>0&&<Disclosure className="feature-excluded" summary={t('{count} unavailable layers',{count:number(selected.arcgis.excludedLayers.length)})}><ul className="feature-excluded-layers">{selected.arcgis.excludedLayers.map(layer=><li key={layer.id}><strong>{layer.name} · {layer.id}</strong><p>{t(layer.reason)}</p></li>)}</ul></Disclosure>}
        {selected.wfs?.excludedLayers.length>0&&<Disclosure className="feature-excluded" summary={t('{count} unavailable feature types',{count:number(selected.wfs.excludedLayers.length)})}><ul className="feature-excluded-layers">{selected.wfs.excludedLayers.map(layer=><li key={layer.id}><strong>{layer.title} · {layer.id}</strong><p>{t(layer.reason)}</p></li>)}</ul></Disclosure>}
        <div className="feature-region"><MapPin size={17} aria-hidden="true"/><div><strong>{t('Current query region')}</strong><p>{validQueryBounds(areaBounds)?areaBounds.map(n=>number(n,{maximumFractionDigits:5})).join(' · '):t('Select a query region on Explore first.')}</p>{areaPolygon&&<p>{t('The polygon is recorded; selection uses its bounding rectangle.')}</p>}</div></div>
        <p className="feature-help">{t(selected.overpass?'One bounded OSM query; no pagination or automatic batches. Use at most 100 km² and 1° per side. Raw OSM elements and geometry dependencies are saved locally.':selected.wfs?'Full feature geometry is retained without clipping. Up to 250 pages, 50,000 features and 20 MiB of original responses; the saved archive is also limited to 20 MiB.':selected.arcgis?'Full feature geometry and attributes are retained. Features are not clipped. Up to 25 batches, 5,000 features and 20 MiB per query.':'Full feature geometry and attributes are retained. Features are not clipped. Up to 25 pages, 50,000 features and 20 MiB per query.')}</p>
        {selected.overpass&&<p className="feature-help">{t('OSM bounding-box selection; full geometry retained. Not an exact polygon clip.')}</p>}
        {selected.wfs&&<p className="feature-help">{t('Features are read twice to check consistency. Original responses are saved locally; export produces the verified WGS84 GeoJSON.')}</p>}
        {selected.overpass&&validQueryBounds(areaBounds)&&!validOverpassBounds(areaBounds)&&<p role="alert" className="vector-error">{t('OSM query region is too large. Choose at most 100 km² and 1° per side.')}</p>}
        <div className="feature-submit"><Button icon={Download} primary disabled={Boolean(busy)||!collection||!filtered.some(c=>c.id===collectionId)||!(selected.overpass?validOverpassBounds(areaBounds):validQueryBounds(areaBounds))||Boolean(selected.wfs&&!wfsFormat)} onClick={query}>{t('Get features and save')}</Button><span>{t('{count} supported collections',{count:number(selected.collections.length)})}</span></div>
      </>}
      {busy&&<div role="status" className="feature-loading"><Spinner/>{t(busy==='query'?(selected?.overpass?'Fetching OSM elements and checking geometry dependencies':selected?.wfs?'Fetching WFS responses and verifying schema and feature counts':selected?.arcgis?'Fetching feature batches and checking IDs and counts':'Fetching all pages and checking features'):'Updating service connection')}</div>}
      {error&&<p role="alert" className="vector-error">{t(error)}</p>}
    </div>}
  </Modal>;
}
function ArcgisLayerDetails({layer,copyright=layer.copyrightText}) {
  const {t,number}=useI18n();
  return <><dt>{t('Fields')}</dt><dd>{t('{count} fields · object ID: {field}',{count:number(layer.fields.length),field:layer.objectIdField})}</dd><dt>{t('Source coordinate system')}</dt><dd>{JSON.stringify(layer.spatialReference)}</dd><dt>{t('Layer metadata SHA-256')}</dt><dd>{layer.metadataSha256}</dd><dt>{t('Copyright attribution')}</dt><dd>{copyright||t('No copyright attribution declared; check source metadata.')}<br/>{t('Copyright attribution is not a dataset license.')}</dd></>;
}
function WfsServiceDetails({source}) {
  const {t}=useI18n();
  return <><dt>{t('Capabilities SHA-256')}</dt><dd>{source.capabilitiesSha256}</dd><dt>{t('Declared fees')}</dt><dd>{source.fees||t('Not declared by service')}</dd><dt>{t('Declared access constraints')}</dt><dd>{source.accessConstraints||t('Not declared by service')}</dd></>;
}
export function FeatureProvenanceDetails({source,geojsonSha256,sourceSha256,sourceBytes}) {
  const {t,number,locale}=useI18n();if(!source)return null;
  const extracted=new Intl.DateTimeFormat(locale||'en',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(source.requestedAt));
  return <>
    <dt>{t('Data service')}</dt><dd>{source.serviceName}<br/>{source.serviceUrl}</dd>
    <dt>{t('Collection')}</dt><dd>{source.collectionTitle} · {source.collectionId}</dd>
    <dt>{t('Query region')}</dt><dd>{source.requestedBounds.map(n=>number(n,{maximumFractionDigits:5})).join(' · ')}</dd>
    <dt>{t('Extracted at')}</dt><dd><time dateTime={source.requestedAt} title={source.requestedAt}>{extracted} UTC</time></dd>
    <dt>{t('Query completeness')}</dt><dd>{t(source.wfs?'Pages: {pages} · {count} features; schema and matching counts checked before and after extraction':source.arcgis?'Batches: {pages} · {count} features; initial and final IDs and counts match':'{pages} pages · {count} features; complete matching query',{pages:number(source.pages.length),count:number(source.featureCount)})}<br/>{t('Full feature geometry; not clipped.')}</dd>
    {source.arcgis&&<><dt>{t('Object ID and count checks')}</dt><dd>{t('Initial: {ids} IDs · {count} features',{ids:number(source.arcgis.idReceipts[0].returned),count:number(source.arcgis.countReceipts[0].returned)})}<br/>{t('Final: {ids} IDs · {count} features',{ids:number(source.arcgis.idReceipts[1].returned),count:number(source.arcgis.countReceipts[1].returned)})}<br/>{t('Checks detect ID and count changes; this is not a transaction snapshot.')}</dd><dt>{t('Saved coordinates')}</dt><dd>{t('Service-converted WGS84 GeoJSON (EPSG:4326).')}</dd><ArcgisLayerDetails layer={source.arcgis.layer}/></>}
    {source.wfs&&<><dt>{t('Service response format')}</dt><dd>{source.wfs.format.id==='gml32'?'GML 3.2':'GeoJSON'} · {source.wfs.format.mime}</dd><dt>{t('Response coordinate system')}</dt><dd>{source.wfs.responseCrs}</dd><dt>{t('Geometry conversion')}</dt><dd>{t(source.wfs.format.id==='gml32'?'GML geometry is converted locally to WGS84 GeoJSON with longitude, latitude coordinates.':'The service GeoJSON is verified as WGS84 longitude, latitude coordinates.')}<br/>{t('Original schema, count and feature responses are retained in the local archive.')}</dd><dt>{t('Schema fields')}</dt><dd>{t('{count} attribute fields · geometry: {field}',{count:number(source.wfs.schema.fields.length),field:source.wfs.schema.geometryField})}<br/>{source.wfs.schema.geometryType}</dd><dt>{t('Schema SHA-256')}</dt><dd>{source.wfs.schema.sha256}</dd><dt>{t('Extraction consistency')}</dt><dd>{t('The schema and matching counts were rechecked. This is not a transaction snapshot.')}</dd>{sourceSha256&&<><dt>{t('Original response archive SHA-256')}</dt><dd>{sourceSha256}</dd><dt>{t('Archive size')}</dt><dd>{t('{bytes} bytes',{bytes:number(sourceBytes)})}</dd></>}{geojsonSha256&&<><dt>{t('Derived GeoJSON SHA-256')}</dt><dd>{geojsonSha256}</dd></>}<WfsServiceDetails source={source.wfs}/></>}
    {source.wfs&&<><dt>{t('Feature consistency check')}</dt><dd>{t('{pages} verification pages; geometry and attributes matched the first read.',{pages:number(source.wfs.verificationPages.length)})}<br/>{t(source.wfs.sortField?'Features were matched using the unique integer property {field}.':'Feature IDs also matched between both reads.',{field:source.wfs.sortField})}</dd><dt>{t('Export format')}</dt><dd>{t('Export produces WGS84 GeoJSON with this source record. The original response archive remains stored locally.')}</dd></>}
    <dt>{t('Dataset license')}</dt><dd>{source.licenseLinks.length?source.licenseLinks.join('\n'):t('No dataset license link declared; check collection metadata before reuse.')}</dd>
  </>;
}
export function OsmProvenanceDetails({source,geojsonSha256}) {
  const {t,number,locale}=useI18n();if(!source)return null;
  const time=value=>new Intl.DateTimeFormat(locale||'en',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(value));
  const counts=value=>t('Nodes: {nodes} · ways: {ways} · relations: {relations}',{nodes:number(value.nodes),ways:number(value.ways),relations:number(value.relations)});
  return <>
    <dt>{t('Data service')}</dt><dd>{source.serviceName}<br/>{source.serviceUrl}</dd>
    <dt>{t('OSM category')}</dt><dd>{t(source.presetTitle)} · {source.preset}</dd>
    <dt>{t('Query region')}</dt><dd>{source.requestedBounds.map(n=>number(n,{maximumFractionDigits:5})).join(' · ')}<br/>{t('OSM bounding-box selection; full geometry retained. Not an exact polygon clip.')}</dd>
    <dt>{t('Extracted at')}</dt><dd><time dateTime={source.requestedAt} title={source.requestedAt}>{time(source.requestedAt)} UTC</time></dd>
    <dt>{t('OSM database time')}</dt><dd><time dateTime={source.dataTimestamp} title={source.dataTimestamp}>{time(source.dataTimestamp)} UTC</time></dd>
    <dt>{t('Selected OSM elements')}</dt><dd>{counts(source.elementCounts)}<br/>{t('{count} elements converted to features',{count:number(source.elementCounts.total)})}</dd>
    <dt>{t('Geometry dependencies')}</dt><dd>{counts(source.dependencyCounts)}<br/>{t('Dependencies are saved in the raw response and are not extra selected features.')}</dd>
    <dt>{t('Original OSM response')}</dt><dd>{t('{bytes} bytes · original response retained',{bytes:number(source.bytes)})}<br/>{source.generator} · API {source.apiVersion}</dd>
    <dt>{t('Response SHA-256')}</dt><dd>{source.responseSha256}</dd>
    {geojsonSha256&&<><dt>{t('Derived GeoJSON SHA-256')}</dt><dd>{geojsonSha256}</dd></>}
    <dt>{t('Geometry conversion')}</dt><dd>{t('GeoJSON is derived from the saved OSM response; original IDs and tags are retained.')}</dd>
    <dt>{t('Copyright notice')}</dt><dd>{source.copyrightText}</dd>
    <dt>{t('Executed Overpass query')}</dt><dd><code className="feature-query-text">{source.query}</code></dd>
  </>;
}
