import React from 'react';
import { readFileSync } from 'node:fs';
import { beforeEach, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { I18nProvider } from './i18n.jsx';
import { RuntimeContext } from './runtime-context.js';
import { DownloadAssetButton, RuntimeJobRows } from './runtime-ui.jsx';
import { ProjectsLibrary } from './projects-ui.jsx';
import { QualityPixelDetails } from './quality-ui.jsx';
import { normalizeScene } from './catalog.js';
import { projectRequest } from './projects-client.js';
import { runtimeRequest } from './runtime-client.js';
import { decodeQuality, qualityPalette, QUALITY_DEFINITION } from './quality.js';
import { MODIS_CRS, MODIS_PIXEL } from './modis.js';
vi.mock('./runtime-client.js',async original=>({...await original(),runtimeRequest:vi.fn()}));
const scene=normalizeScene(JSON.parse(readFileSync('prototype/qa/modis-quality-catalog-item.json','utf8')),'planetary-modis');
const project={...projectRequest({name:'MODIS quality',bounds:[-122.55,37.68,-122.32,37.84],scenes:[scene]}),id:'qa-project'};
const jobs=['modis_qc','modis_state'].map((key,i)=>({id:`qa-${i}`,kind:'download',status:'succeeded',itemId:scene.id,assetKey:key,href:scene.assets[key].href,mediaType:scene.assets[key].type,sha256:'a'.repeat(64),bytesDownloaded:1024}));
const wrap=(children,extra={})=>render(<I18nProvider><RuntimeContext.Provider value={{health:{},jobs,projects:[project],refresh:vi.fn(),act:vi.fn(),...extra}}>{children}</RuntimeContext.Provider></I18nProvider>);
beforeEach(()=>{vi.resetAllMocks();delete window.__TAURI__;Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:()=> 'en',setItem:vi.fn()}});});

it('MODIS can queue all five original COGs together while explaining that decoding does not apply a quality mask',async()=>{
  runtimeRequest.mockImplementation(async(operation,payload)=>operation==='createProject'?project:{jobs:[{id:payload.assetKey}]});
  wrap(<DownloadAssetButton scene={scene} areaBounds={project.bounds} areaName="MODIS"/>);
  await userEvent.click(screen.getByRole('button',{name:'Create project and download'}));
  await userEvent.click(screen.getByRole('combobox',{name:'Download content'}));
  await userEvent.click(screen.getByRole('option',{name:'RGB bands + quality + pixel state · 5 files'}));
  expect(screen.getByText(/does not apply a cloud or quality mask/)).toBeTruthy();
  await userEvent.click(screen.getByRole('button',{name:'Create project and start download'}));
  await screen.findByRole('button',{name:'Open project'});
  expect(runtimeRequest.mock.calls.slice(1).map(([,payload])=>payload.assetKey)).toEqual(['red','green','blue','modis_qc','modis_state']);
  expect(runtimeRequest.mock.calls[0][1].scenes[0].assets.modis_qc.rasterBand).toBeUndefined();
});
it('a five-file MODIS project processes downloaded quality layers separately and keeps reflectance readiness independent',async()=>{
  runtimeRequest.mockResolvedValue([project]);
  const act=vi.fn();
  wrap(<ProjectsLibrary focusedProjectId={project.id}/>,{act});
  await screen.findByRole('heading',{name:project.name});
  expect(screen.getByRole('progressbar',{name:'MODIS band quality · Files ready'}).getAttribute('aria-valuenow')).toBe('1');
  expect(screen.getByRole('progressbar',{name:'MODIS pixel state · Files ready'}).getAttribute('aria-valuenow')).toBe('1');
  expect(screen.getAllByRole('button',{name:'Clip band to project area'})).toHaveLength(3);
  const qualityButtons=screen.getAllByRole('button',{name:'Clip quality to project area'});
  expect(qualityButtons).toHaveLength(2);expect(qualityButtons.every(button=>!button.disabled)).toBe(true);
  expect(screen.getAllByRole('button',{name:'Clip band to project area'}).every(button=>button.disabled)).toBe(true);
  await userEvent.click(qualityButtons[0]);
  expect(act).toHaveBeenCalledWith('mosaicProject',{id:project.id,assetKey:'modis_qc'});
  expect(screen.queryByRole('button',{name:/Clip SCL/})).toBeNull();
});
it('Landsat saturation processing waits for matching pixel-quality downloads without blocking other quality',async()=>{
  const landsat=normalizeScene(JSON.parse(readFileSync('prototype/public/samples/landsat-quality-response.json','utf8')).features[0],'planetary-landsat');
  const p={...projectRequest({name:'Landsat quality',bounds:[-122.55,37.68,-122.32,37.84],scenes:[landsat]}),id:'landsat-qa-project'};
  const originals=['qa_radsat'].map(key=>({id:key,kind:'download',status:'succeeded',itemId:landsat.id,assetKey:key,href:landsat.assets[key].href,mediaType:landsat.assets[key].type,sha256:'a'.repeat(64),bytesDownloaded:1024}));
  runtimeRequest.mockResolvedValue([p]);
  const act=vi.fn();
  const view=wrap(<ProjectsLibrary focusedProjectId={p.id}/>,{jobs:originals,projects:[p],act});
  await screen.findByRole('heading',{name:p.name});
  expect(screen.getByText('Download matching pixel-quality files before processing saturation flags.')).toBeTruthy();
  expect(screen.getAllByRole('button',{name:'Clip quality to project area'}).every(button=>button.disabled)).toBe(true);
  view.unmount();
  originals.push({...originals[0],id:'qa_pixel',assetKey:'qa_pixel',href:landsat.assets.qa_pixel.href});
  wrap(<ProjectsLibrary focusedProjectId={p.id}/>,{jobs:originals,projects:[p],act});
  await screen.findByRole('heading',{name:p.name});
  const buttons=screen.getAllByRole('button',{name:'Clip quality to project area'});
  expect(buttons.every(button=>!button.disabled)).toBe(true);
  await userEvent.click(buttons[1]);
  expect(act).toHaveBeenCalledWith('mosaicProject',{id:p.id,assetKey:'qa_radsat'});
});
it('quality inspection has its own unsigned type, full tile counts and official definitions instead of an SCL legend',async()=>{
  const data={width:2400,height:2400,bandCount:1,dataType:'UInt32',nodata:4294967295,crs:MODIS_CRS,sha256:jobs[0].sha256,pixelSize:[MODIS_PIXEL,MODIS_PIXEL],bounds:[-10*2400*MODIS_PIXEL,3*2400*MODIS_PIXEL,-9*2400*MODIS_PIXEL,4*2400*MODIS_PIXEL],previewWidth:1,previewHeight:1,previewDataUrl:'data:image/png;base64,AAAA',classes:qualityPalette('modis_qc').map(([label,color],value)=>({value,label,color,count:value===0?5759999:0})),quality:{product:'modis-09a1-v061',band:'modis_qc',layer:'sur_refl_qc_500m',pixelInterpretation:'PixelIsArea',displayField:'MODLAND quality',sampleCount:5760000,validSampleCount:5759999,countsFullResolution:true,definition:QUALITY_DEFINITION}};
  runtimeRequest.mockImplementation(async operation=>operation==='raster'?data:null);
  wrap(<RuntimeJobRows jobs={[jobs[0]]} library/>);
  await userEvent.click(screen.getByRole('button',{name:'File details and provenance'}));
  await userEvent.click(screen.getByRole('button',{name:'Inspect raster'}));
  await screen.findByRole('heading',{name:'Raster metadata'});
  expect(screen.getByText('Original quality flags and file geometry')).toBeTruthy();
  expect(screen.getByText('UInt32')).toBeTruthy();expect(screen.queryByText('Scene classes')).toBeNull();
  await userEvent.click(screen.getByRole('button',{name:'MODLAND quality'}));
  expect(screen.getByText(/Full raster counts for this file; not a cloud-cover estimate/)).toBeTruthy();
  expect(screen.getByRole('link',{name:'NASA quality flag definitions'}).getAttribute('href')).toBe(QUALITY_DEFINITION);
});
it('a successful replacement keeps an old source failure in task history without leaving a false project action',async()=>{
  runtimeRequest.mockResolvedValue([project]);
  const old={...jobs[1],id:'old-failed',status:'failed',sha256:null};
  const history=[old,...jobs];
  wrap(<ProjectsLibrary focusedProjectId={project.id}/>,{jobs:history});
  await screen.findByRole('heading',{name:project.name});
  expect(screen.queryByText('Project downloads and processing')).toBeNull();
  expect(history).toHaveLength(3);expect(history[0].status).toBe('failed');
});
it('Chinese pixel details keep undefined codes explicit and translate Collection 6.1 salt-pan and internal-snow fields',async()=>{
  Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:()=> 'zh-CN',setItem:vi.fn()}});
  wrap(<QualityPixelDetails pixel={{isNoData:false,quality:decodeQuality('modis_state',2**14+2**15)}}/>);
  await userEvent.click(screen.getByRole('button',{name:'解码质量标记'}));
  expect(screen.getByText('盐滩')).toBeTruthy();expect(screen.getByText('内部雪检测')).toBeTruthy();expect(screen.getByText(/0xC000/)).toBeTruthy();
  expect(screen.getAllByText(/^是 · 1/)).toHaveLength(2);
});
