import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,webcrypto} from 'node:crypto';
import {createThreeDScene,rewriteThreeDResource,threeDOrder,threeDRequest,validateThreeDPackage} from './three-d-client.js';
const sha=b=>createHash('sha256').update(b).digest('hex');
function fixture(){const b=new TextEncoder().encode(JSON.stringify({asset:{version:'2.0'},buffers:[{uri:'mesh.bin',byteLength:12}]})),bin=new Uint8Array(12),id='d78f675e-869c-43bd-9721-c94172fa86c9';const resources=[{id:sha('model.gltf'),locator:'model.gltf',sha256:sha(b),bytes:b.length,kind:'gltf',links:[{reference:{pointer:'/buffers/0/uri',uri:'mesh.bin',purpose:'buffer',minBytes:12},target:sha('mesh.bin')}],etag:null,lastModified:null},{id:sha('mesh.bin'),locator:'mesh.bin',sha256:sha(bin),bytes:bin.length,kind:'buffer',links:[],etag:null,lastModified:null}];const asset={id,name:'Synthetic model fixture',origin:'local-files',source:'model.gltf',rights:{license:'Test fixture',attribution:'Synthetic test data',permissionConfirmed:true,licenseUrl:null},createdAt:'2026-10-03T00:00:00Z',entry:resources[0].id,resources,bytes:b.length+bin.length,tileCount:0,receiptSha256:sha('receipt')};return{asset,data:new Map([[resources[0].id,b],[resources[1].id,bin]])};}
test('3D dependency order handles nested scenes and rejects cycles, omitted and unreferenced resources',()=>{const{asset}=fixture();assert.deepEqual(threeDOrder(asset).map(r=>r.kind),['buffer','gltf']);const missing=structuredClone(asset);missing.resources.pop();assert.throws(()=>threeDOrder(missing),/missing/);const cycle=structuredClone(asset);cycle.resources[1].links=[{target:asset.entry}];assert.throws(()=>threeDOrder(cycle),/Cyclic/);const extra=structuredClone(asset);extra.resources.push({...asset.resources[1],id:sha('extra')});assert.throws(()=>threeDOrder(extra),/unreferenced/);});
test('3D packages reject changed receipt membership and unchecked rights',()=>{const{asset}=fixture();assert.equal(validateThreeDPackage(asset),asset);for(const edit of[p=>p.bytes++,p=>p.rights.permissionConfirmed=false,p=>p.resources[0].links[0].target=sha('absent'),p=>p.resources[0].sha256='bad']){const bad=structuredClone(asset);edit(bad);assert.throws(()=>validateThreeDPackage(bad));}});
test('source and imported license links require public HTTPS and preserve upstream receipt validation',()=>{
  const{asset}=fixture();
  for(const licenseUrl of['javascript:alert(1)','https://example.com/terms?token=secret','http://example.com/terms','https://user:pass@example.com/terms','https://127.0.0.1/terms']){
    const bad=structuredClone(asset);bad.rights.licenseUrl=licenseUrl;assert.throws(()=>validateThreeDPackage(bad));
  }
  const copy=structuredClone(asset);copy.origin='local-archive';copy.importedFrom={source:asset.source,origin:asset.origin,sourceReceiptSha256:asset.receiptSha256,rights:structuredClone(asset.rights)};
  assert.equal(validateThreeDPackage(copy),copy);
  const imported=structuredClone(copy);imported.resourceOrigin={origin:'local-files',source:asset.source};assert.equal(validateThreeDPackage(imported),imported);
  const excessive=structuredClone(copy);let leaf=excessive.importedFrom;for(let depth=0;depth<8;depth++){leaf.previous=structuredClone(copy.importedFrom);leaf=leaf.previous;}assert.throws(()=>validateThreeDPackage(excessive),/imported/);
  const unknown=structuredClone(imported);unknown.resourceOrigin={origin:'public-https',source:'javascript:alert(1)'};assert.throws(()=>validateThreeDPackage(unknown),/origin/);
  for(const edit of[p=>p.importedFrom.sourceReceiptSha256='wrong',p=>p.importedFrom.rights.permissionConfirmed=false,p=>p.importedFrom.rights.licenseUrl='javascript:alert(1)',p=>p.origin='local-files']){
    const bad=structuredClone(copy);edit(bad);assert.throws(()=>validateThreeDPackage(bad),/imported/);
  }
});
test('localizing a model changes only declared URIs and preserves buffers and transforms',()=>{const{asset,data}=fixture();const r=asset.resources[0],out=rewriteThreeDResource(data.get(r.id),r,new Map([[asset.resources[1].id,'blob:test-buffer']]));const v=JSON.parse(new TextDecoder().decode(out));assert.equal(v.buffers[0].uri,'blob:test-buffer');assert.equal(v.buffers[0].byteLength,12);assert.deepEqual(v.asset,{version:'2.0'});const bad=structuredClone(r);bad.links[0].reference.uri='wrong.bin';assert.throws(()=>rewriteThreeDResource(data.get(r.id),bad,new Map([[asset.resources[1].id,'blob:a']])),/pointer changed/);});
test('scene blobs verify original bytes, follow dependencies and release every URL',async()=>{globalThis.crypto??=webcrypto;const{asset,data}=fixture(),blobs=[],revoked=[],progress=[];const scene=await createThreeDScene(asset,{request:async(_op,p)=>({resource:asset.resources.find(r=>r.id===p.resourceId),dataBase64:Buffer.from(data.get(p.resourceId)).toString('base64')}),createUrl:b=>{blobs.push(b);return'blob:'+blobs.length;},revokeUrl:u=>revoked.push(u),onProgress:(a,b)=>progress.push([a,b])});assert.equal(scene.url,'blob:2');assert.equal(scene.kind,'gltf');assert.equal(JSON.parse(await blobs[1].text()).buffers[0].uri,'blob:1');assert.deepEqual(progress,[[1,2],[2,2]]);scene.dispose();scene.dispose();assert.deepEqual(revoked,['blob:1','blob:2']);});
test('a damaged or aborted scene releases already-created blobs and never renders partial content',async()=>{const{asset,data}=fixture(),created=[],revoked=[];await assert.rejects(createThreeDScene(asset,{request:async(_op,p)=>({resource:asset.resources.find(r=>r.id===p.resourceId),dataBase64:Buffer.from(p.resourceId===asset.entry?new Uint8Array(1):data.get(p.resourceId)).toString('base64')}),createUrl:()=>{created.push('blob:a');return'blob:a';},revokeUrl:u=>revoked.push(u)}),/SHA-256/);assert.deepEqual(created,revoked);const controller=new AbortController();controller.abort();await assert.rejects(createThreeDScene(asset,{signal:controller.signal,request:()=>{throw new Error('Should not read');}}),{name:'AbortError'});});
test('3D native dispatch preserves the full acquisition pin and source declarations',async()=>{const previous=globalThis.window,{asset}=fixture(),calls=[];globalThis.window={__TAURI__:{core:{invoke:async(command,payload)=>{calls.push({command,payload});return asset;}}}};try{const request={url:'https://assets.example.com/tileset.json',discoverySha256:sha('root'),name:asset.name,rights:asset.rights};assert.equal(await threeDRequest('save',request),asset);assert.deepEqual(calls,[{command:'acquire_three_d',payload:{request}}]);await assert.rejects(threeDRequest('inspect',{id:'../outside'}),/identifier/);assert.equal(calls.length,1);}finally{globalThis.window=previous;}});
