import React,{useEffect,useRef,useState} from 'react';
import {Map as MapIcon,Plug,Plus,Trash2,RefreshCw,Download,MapPin,Layers,Info,FolderOpen} from 'lucide-react';
import {Modal,Button,Input,Select,Disclosure,Spinner,EmptyState} from './ui/index.jsx';
import {tileRequest,tileSelection,exportTilePackage,openTilePackage,pmtilesExample,tileAttribution,tileFormat} from './tiles-client.js';
import {desktopAvailable} from './runtime-client.js';
import {useI18n} from './i18n.jsx';
import './features.css';import './vector.css';import './tiles.css';
export function TileSourceDetails({asset}) {
  const {t,number,locale}=useI18n(),s=asset.source;
  const connected=new Intl.DateTimeFormat(locale||'en',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'}).format(new Date(s.connectedAt));
  return <dl className="vector-properties"><dt>{t('Tile source')}</dt><dd>{s.local?s.local.fileName:<>{s.name}<br/>{s.url}</>}</dd>{s.local&&<><dt>{t('File storage')}</dt><dd>{t('Managed copy')} · {t('Original archive preserved')}</dd></>}<dt>{t('Tile levels')}</dt><dd>{asset.minZoom}–{asset.maxZoom} · EPSG:3857 · {tileFormat(asset)==='pbf'?'MVT':tileFormat(asset).toUpperCase()}</dd><dt>{t('Saved tiles')}</dt><dd>{number(asset.tiles.length)}{!s.local&&<> · {t('{count} absent tiles',{count:number(asset.absent.length)})}</>}</dd><dt>{t(s.local?'Archive bounds':'Requested bounds')}</dt><dd>{asset.requestedBounds.map(n=>number(n,{maximumFractionDigits:5})).join(' · ')}</dd><dt>{t('Tile coverage bounds')}</dt><dd>{asset.tileCoverageBounds.map(n=>number(n,{maximumFractionDigits:5})).join(' · ')}</dd><dt>{t('Attribution')}</dt><dd>{tileAttribution(s.metadata)||t('Not declared by source')}</dd><dt>{t(s.local?'Imported at':'Source version')}</dt><dd>{!s.local&&<>{s.etag}<br/></>}<time dateTime={s.connectedAt} title={s.connectedAt}>{connected} UTC</time></dd><dt>{t('Package SHA-256')}</dt><dd className="mono">{asset.sha256}</dd><dt>{t('Discovery SHA-256')}</dt><dd className="mono">{s.discoverySha256}</dd></dl>;
}
export function TileSourceDialog({areaBounds,onClose,onSaved}) {
  const {t,number}=useI18n();const[sources,setSources]=useState([]),[sourceId,setSourceId]=useState(''),[loading,setLoading]=useState(true),[adding,setAdding]=useState(false),[name,setName]=useState(''),[url,setUrl]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[min,setMin]=useState(0),[max,setMax]=useState(0);
  useEffect(()=>{const a=new AbortController();tileRequest('sources',{},a.signal).then(s=>{setSources(s);setSourceId(s[0]?.id||'');setAdding(!s.length);}).catch(e=>{if(!a.signal.aborted){setError(e.message);setAdding(true);}}).finally(()=>{if(!a.signal.aborted)setLoading(false);});return()=>a.abort();},[]);
  const source=sources.find(s=>s.id===sourceId),h=source?.header;
  useEffect(()=>{if(h){setMin(h.minZoom);setMax(Math.min(h.maxZoom,h.minZoom+7));}},[h]);
  let plan=null,planError='';if(source){try{plan=tileSelection(areaBounds,min,max);}catch(e){planError=e.message;}}
  const run=async(kind,action)=>{setBusy(kind);setError('');try{await action();}catch(e){setError(e.message);}finally{setBusy('');}};
  const connect=()=>run('connect',async()=>{const s=await tileRequest('connect',{name,url});setSources(ss=>[...ss.filter(v=>v.id!==s.id),s]);setSourceId(s.id);setAdding(false);});
  const extract=()=>run('extract',async()=>{const p=await tileRequest('extract',{sourceId,bounds:areaBounds,minZoom:min,maxZoom:max});onSaved(p);onClose();});
  return <Modal className="feature-service-dialog" title={t('Extract offline tiles')} description={t('Save the tile pyramid for your current search region.')} onClose={onClose} closeDisabled={Boolean(busy)} closeLabel={t('Close')}>
    {loading?<div className="feature-loading"><Spinner/>{t('Loading tile sources')}</div>:<div className="feature-service-body">
      {!adding&&<div className="feature-service-row"><label className="feature-field"><span>{t('Tile source')}</span><Select aria-label={t('Tile source')} value={sourceId} disabled={Boolean(busy)} onChange={e=>setSourceId(e.target.value)}>{sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></label><div className="feature-service-icons"><Button size="icon" variant="secondary" aria-label={t('Add tile source')} tooltip={t('Add tile source')} disabled={Boolean(busy)} onClick={()=>setAdding(true)}><Plus size={16}/></Button><Button size="icon" variant="secondary" aria-label={t('Refresh tile source')} tooltip={t('Refresh tile source')} disabled={Boolean(busy)} onClick={()=>run('refresh',async()=>{const s=await tileRequest('connect',{name:source.name,url:source.url});setSources(ss=>ss.map(v=>v.id===s.id?s:v));})}><RefreshCw size={16}/></Button><Button size="icon" variant="quiet" aria-label={t('Remove tile source')} tooltip={t('Remove tile source')} disabled={Boolean(busy)} onClick={()=>run('forget',async()=>{await tileRequest('forget',{id:sourceId});const ss=sources.filter(v=>v.id!==sourceId);setSources(ss);setSourceId(ss[0]?.id||'');setAdding(!ss.length);})}><Trash2 size={16}/></Button></div></div>}
      {adding&&<section className="feature-connect"><label className="feature-field"><span>{t('Connection name')}</span><Input aria-label={t('Connection name')} maxLength={80} value={name} disabled={Boolean(busy)} onChange={e=>setName(e.target.value)}/></label><label className="feature-field"><span>{t('PMTiles archive URL')}</span><Input aria-label={t('PMTiles archive URL')} maxLength={2048} placeholder="https://…/tiles.pmtiles" value={url} disabled={Boolean(busy)} onChange={e=>setUrl(e.target.value)}/></label><div className="feature-connect-actions"><Button primary icon={Plug} disabled={Boolean(busy)||!name.trim()||!url.trim()} onClick={connect}>{t('Connect service')}</Button><Button variant="quiet" disabled={Boolean(busy)} onClick={()=>{setName(pmtilesExample.name);setUrl(pmtilesExample.url);}}>{t('Use public PMTiles sample')}</Button>{sources.length>0&&<Button variant="quiet" disabled={Boolean(busy)} onClick={()=>setAdding(false)}>{t('Cancel')}</Button>}</div><p className="feature-help">{t('Public HTTPS PMTiles v3 with MVT tiles, range requests and a stable version. Uses your proxy settings.')}</p></section>}
      {!adding&&source&&<><div className="tiles-options">{[['Minimum level',min,setMin],['Maximum level',max,setMax]].map(([label,value,setter])=><label className="feature-field" key={label}><span>{t(label)}</span><Select aria-label={t(label)} value={String(value)} disabled={Boolean(busy)} onChange={e=>setter(Number(e.target.value))}>{Array.from({length:h.maxZoom-h.minZoom+1},(_,i)=>h.minZoom+i).map(z=><option key={z} value={String(z)}>{z}</option>)}</Select></label>)}</div><div className="feature-region"><MapPin size={17}/><div><strong>{t('Current query region')}</strong><p>{areaBounds?.map(n=>number(n,{maximumFractionDigits:5})).join(' · ')||t('Select a query region on Explore first.')}</p>{plan&&<p>{t('{count} candidate tiles',{count:number(plan.length)})} · EPSG:3857</p>}</div></div><p className="feature-help">{t('Includes whole intersecting tiles at each selected level. Tile geometry is simplified and may include a buffer; it is not clipped to your polygon. Maximum 512 tiles and 128 MiB.')}</p><Disclosure summary={t('Layer information')}><p className="feature-description">{source.metadata.vector_layers.map(l=>l.id).join(' · ')}</p>{typeof source.metadata.attribution==='string'&&<p className="feature-description">{tileAttribution(source.metadata)}</p>}</Disclosure>{planError&&<p className="vector-error" role="alert">{t(planError)}</p>}<div className="feature-submit"><Button primary icon={Download} disabled={Boolean(busy)||!plan} onClick={extract}>{t('Save offline tile package')}</Button></div></>}
      {busy&&<div className="feature-loading" role="status"><Spinner/>{t(busy==='extract'?'Extracting and verifying tiles':'Reading PMTiles metadata')}</div>}{error&&<p role="alert" className="vector-error">{t(error)}</p>}
    </div>}
  </Modal>;
}
export function TileLibrary({areaBounds}) {
  const {t,number}=useI18n();const[packages,setPackages]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[open,setOpen]=useState(false),[details,setDetails]=useState(null);
  const input=useRef(null),native=desktopAvailable();
  useEffect(()=>{const a=new AbortController();setLoading(true);tileRequest('list',{},a.signal).then(ps=>setPackages([...ps].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)))).catch(e=>{if(!a.signal.aborted)setError(e.message);}).finally(()=>{if(!a.signal.aborted)setLoading(false);});return()=>a.abort();},[revision]);
  const exportFile=async id=>{setBusy(true);setError('');try{await exportTilePackage(id);}catch(e){setError(e.message);}finally{setBusy(false);}};
  const importFile=async file=>{setBusy(true);setError('');try{const p=await openTilePackage(file);if(p)setRevision(r=>r+1);}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <section aria-label={t('Offline tiles')}><div className="vector-toolbar"><Button primary icon={FolderOpen} disabled={busy} onClick={()=>native?importFile():input.current?.click()}>{t('Open tile file')}</Button><Button variant="secondary" icon={Plug} disabled={busy} onClick={()=>setOpen(true)}>{t('Extract offline tiles')}</Button><Button size="icon" variant="secondary" aria-label={t('Refresh tile packages')} tooltip={t('Refresh tile packages')} disabled={loading||busy} onClick={()=>{setError('');setRevision(r=>r+1);}}><RefreshCw size={16}/></Button>{busy&&<Spinner aria-label={t('Processing tile package')}/>}<span className="vector-count">{t('{count} offline packages',{count:number(packages.length)})}</span><Input ref={input} type="file" accept=".pmtiles,.mbtiles" hidden aria-label={t('Choose tile file')} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)importFile(file);}}/></div><p className="vector-source-note">{t('Open PMTiles vectors or MBTiles vectors and images, up to 128 MiB and 512 tiles. A verified copy stays available offline.')}</p>{error&&<p role="alert" className="vector-error">{t(error)}</p>}{loading&&<div className="feature-loading"><Spinner/>{t('Loading tile packages')}</div>}{!loading&&!packages.length&&!error&&<EmptyState icon={MapIcon} title={t('No offline tile packages')} description={t('Open a local PMTiles or MBTiles file, or extract a public archive for your area.')}/>}<div className="tiles-package-grid">{packages.map(p=><article className="tiles-package" key={p.id}><div className="tiles-package-icon"><MapIcon size={24}/></div><div className="tiles-package-copy"><strong title={p.name}>{p.name}</strong><p>{p.source?.mbtiles?'MBTiles':'PMTiles'} · {p.minZoom}–{p.maxZoom} · {t('{count} tiles',{count:number(p.tiles.length)})} · {number(p.bytes/1048576,{maximumFractionDigits:1})} MiB</p><div className="vector-file-actions"><Button asChild size="icon" variant="secondary" tooltip={t('Open in workspace')}><a href={`#Workspace?tiles=${p.id}`} aria-label={t('Open in workspace')}><Layers size={16}/></a></Button><Button size="icon" variant="secondary" aria-label={t('Export tile package')} tooltip={t('Export tile package')} disabled={busy} onClick={()=>exportFile(p.id)}><Download size={16}/></Button><Button size="icon" variant="secondary" aria-label={t('Tile source details')} tooltip={t('Tile source details')} onClick={()=>setDetails(p)}><Info size={16}/></Button></div></div></article>)}</div>{open&&<TileSourceDialog areaBounds={areaBounds} onClose={()=>setOpen(false)} onSaved={()=>setRevision(r=>r+1)}/>} {details&&<Modal title={t('Tile source details')} className="feature-service-dialog" onClose={()=>setDetails(null)} closeLabel={t('Close')}><TileSourceDetails asset={details}/></Modal>}</section>;
}
