import React from 'react';import {describe,it,expect,vi,beforeEach} from 'vitest';import {render,screen,waitFor} from '@testing-library/react';import userEvent from '@testing-library/user-event';
import {TileSourceDialog,TileLibrary,TileSourceDetails} from './tiles-ui.jsx';import {tileRequest,openTilePackage} from './tiles-client.js';
vi.mock('./i18n.jsx',()=>({useI18n:()=>({t:s=>s,number:String})}));vi.mock('./tiles-client.js',async importOriginal=>({...await importOriginal(),tileRequest:vi.fn(),openTilePackage:vi.fn()}));
const source={id:'source',name:'Fixture only',url:'https://example.com/fixture.pmtiles',header:{minZoom:4,maxZoom:7},metadata:{vector_layers:[{id:'polygons'}]}};
beforeEach(()=>{tileRequest.mockReset();openTilePackage.mockReset();});
describe('PMTiles extraction controls',()=>{
 it('uses explicit levels and the current area in native requests',async()=>{const user=userEvent.setup(),saved=vi.fn(),close=vi.fn();tileRequest.mockResolvedValueOnce([source]).mockResolvedValueOnce({id:'result'});render(<TileSourceDialog areaBounds={[-122.55,37.65,-122.32,37.85]} onClose={close} onSaved={saved}/>);await screen.findByRole('combobox',{name:'Minimum level'});expect(screen.getByText(/Includes whole intersecting tiles/)).toBeTruthy();expect(screen.getByText(/\{count\} candidate tiles/)).toBeTruthy();await user.click(screen.getByRole('button',{name:'Save offline tile package'}));await waitFor(()=>expect(saved).toHaveBeenCalledWith({id:'result'}));expect(tileRequest).toHaveBeenLastCalledWith('extract',{sourceId:'source',bounds:[-122.55,37.65,-122.32,37.85],minZoom:4,maxZoom:7});expect(close).toHaveBeenCalled();});
 it('prevents extraction that exceeds 512 tiles',async()=>{tileRequest.mockResolvedValueOnce([source]);render(<TileSourceDialog areaBounds={[-170,-70,170,70]} onClose={()=>{}} onSaved={()=>{}}/>);await screen.findByRole('combobox',{name:'Minimum level'});expect(screen.getByRole('alert').textContent).toContain('512');expect(screen.getByRole('button',{name:'Save offline tile package'}).disabled).toBe(true);});
 it('leaves failures visible without publishing a saved package',async()=>{const user=userEvent.setup(),saved=vi.fn();tileRequest.mockResolvedValueOnce([source]).mockRejectedValueOnce(new Error('PMTiles archive changed'));render(<TileSourceDialog areaBounds={[10,10,11,11]} onClose={()=>{}} onSaved={saved}/>);await screen.findByRole('combobox',{name:'Minimum level'});await user.click(screen.getByRole('button',{name:'Save offline tile package'}));expect((await screen.findByRole('alert')).textContent).toBe('PMTiles archive changed');expect(saved).not.toHaveBeenCalled();});
});
describe('local PMTiles controls',()=>{
 it('imports a chosen file and refreshes only after a saved package',async()=>{const user=userEvent.setup();tileRequest.mockResolvedValueOnce([]).mockResolvedValueOnce([{id:'result',name:'Local file',minZoom:4,maxZoom:7,tiles:[{}],bytes:200,createdAt:'2026-10-03'}]);openTilePackage.mockResolvedValueOnce({id:'result'});render(<TileLibrary/>);await screen.findByText('No offline tile packages');const f=new File([new Uint8Array(200)],'地图.pmtiles');await user.upload(screen.getByLabelText('Choose tile file'),f);await screen.findByText('Local file');expect(openTilePackage).toHaveBeenCalledWith(f);expect(tileRequest.mock.calls.filter(c=>c[0]==='list')).toHaveLength(2);});
 it('keeps an import failure visible and retains the original list',async()=>{const user=userEvent.setup();tileRequest.mockResolvedValueOnce([]);openTilePackage.mockRejectedValueOnce(new Error('Local PMTiles header counts do not match its directory'));render(<TileLibrary/>);await screen.findByText('No offline tile packages');await user.upload(screen.getByLabelText('Choose tile file'),new File([new Uint8Array(200)],'bad.pmtiles'));expect((await screen.findByRole('alert')).textContent).toContain('counts');expect(tileRequest).toHaveBeenCalledTimes(1);expect(screen.getByRole('button',{name:'Open tile file'}).disabled).toBe(false);});
 it('describes a managed local copy without a fabricated URL or ETag',()=>{render(<TileSourceDetails asset={{minZoom:2,maxZoom:2,tiles:[{}],absent:[],requestedBounds:[0,0,1,1],tileCoverageBounds:[0,0,1,1],sha256:'a'.repeat(64),source:{name:'Local',url:'',etag:'',connectedAt:'2026-10-03',discoverySha256:'b'.repeat(64),local:{fileName:'地图.pmtiles'},metadata:{}}}}/>);expect(screen.getByText('地图.pmtiles')).toBeTruthy();expect(screen.getByText(/Original archive preserved/)).toBeTruthy();expect(screen.queryByText('Source version')).toBe(null);expect(screen.getByText('Archive bounds')).toBeTruthy();});
});
describe('local MBTiles controls',()=>{
 it('imports MBTiles through the shared picker and identifies the saved format',async()=>{const user=userEvent.setup();tileRequest.mockResolvedValueOnce([]).mockResolvedValueOnce([{id:'mb-result',name:'Image fixture only',minZoom:4,maxZoom:7,tiles:[{}],bytes:200,createdAt:'2026-10-03',source:{mbtiles:{format:'png'}}}]);openTilePackage.mockResolvedValueOnce({id:'mb-result'});render(<TileLibrary/>);await screen.findByText('No offline tile packages');const input=screen.getByLabelText('Choose tile file');expect(input.accept).toBe('.pmtiles,.mbtiles');const file=new File([new Uint8Array(200)],'图片.mbtiles');await user.upload(input,file);await screen.findByText('Image fixture only');expect(openTilePackage).toHaveBeenCalledWith(file);expect(screen.getByText(/^MBTiles · 4–7/)).toBeTruthy();expect(screen.getByRole('link',{name:'Open in workspace'}).getAttribute('href')).toBe('#Workspace?tiles=mb-result');});
});
