import React,{useEffect,useRef,useState} from 'react';
import Map from 'ol/Map.js';import View from 'ol/View.js';import ImageLayer from 'ol/layer/Image.js';import ImageStatic from 'ol/source/ImageStatic.js';
import VectorLayer from 'ol/layer/Vector.js';import VectorSource from 'ol/source/Vector.js';import GeoJSON from 'ol/format/GeoJSON.js';import {Style,Fill,Stroke} from 'ol/style.js';
import {Image as ImageIcon,FolderOpen,Maximize,Download} from 'lucide-react';
import {Button,Spinner,Disclosure,ResizableGroup,ResizablePanel,ResizeHandle} from './ui/index.jsx';import {useI18n} from './i18n.jsx';import {mapRequest,exportMapImage} from './wms-client.js';import {MapSourceDetails,layerTitle} from './wms-ui.jsx';
import 'ol/ol.css';import './wms.css';import './vector.css';
import {mapProtocol} from './arcgis-map-client.js';
export function MapImageWorkspace({id}) {
  const {t}=useI18n();const[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const target=useRef(null),map=useRef(null);
  useEffect(()=>{const abort=new AbortController();setData(null);setError('');mapRequest('inspect',{id},abort.signal).then(setData).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[id]);
  useEffect(()=>{if(!data||!target.current)return;
    const a=data.asset,theme=()=>{const s=getComputedStyle(target.current);return new Style({fill:new Fill({color:s.getPropertyValue('--canvas').trim()}),stroke:new Stroke({color:s.getPropertyValue('--line-strong').trim(),width:1})});};
    const land=new VectorLayer({source:new VectorSource({url:'./basemaps/natural-earth-50m-land.geojson',format:new GeoJSON(),wrapX:false}),style:theme()});
    const image=new ImageLayer({source:new ImageStatic({url:data.imageUrl,projection:a.crs,imageExtent:a.imageExtent||a.bounds})});
    const instance=new Map({target:target.current,layers:[land,image],view:new View({projection:'EPSG:4326',center:[(a.bounds[0]+a.bounds[2])/2,(a.bounds[1]+a.bounds[3])/2],zoom:4}),controls:[]});map.current=instance;
    instance.getView().fit(a.bounds,{padding:[32,32,32,32],duration:200});
    const resize=new ResizeObserver(()=>instance.updateSize());resize.observe(target.current);const observer=new MutationObserver(()=>land.setStyle(theme()));observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme','class','style']});
    return()=>{resize.disconnect();observer.disconnect();instance.setTarget(undefined);map.current=null;};
  },[data]);
  const asset=data?.asset;const save=async()=>{setBusy(true);setError('');try{await exportMapImage(id);}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <main className="vector-workspace" aria-label={t('Map image workspace')}><ResizableGroup orientation="horizontal" storageKey="map-image-workspace" panelIds={['map-image-details','map-image-map']}><ResizablePanel id="map-image-details" defaultSize="300px" minSize="240px" maxSize="480px"><aside className="vector-inspector"><div className="vector-inspector-heading"><ImageIcon size={20}/><h2>{asset?layerTitle(asset.source.layerTitle):t('Map image workspace')}</h2></div><Button asChild variant="secondary" size="sm"><a href="#My%20Data?view=maps"><FolderOpen size={16}/>{t('Map images')}</a></Button>{asset&&<><p className="vector-source-note">{asset.source.serviceName} · {asset.source.time||mapProtocol(asset.source)}<br/>{asset.width} × {asset.height} · {asset.crs}</p><div className="vector-map-actions"><Button size="icon" variant="secondary" aria-label={t('Fit map image')} tooltip={t('Fit map image')} onClick={()=>map.current?.getView().fit(asset.bounds,{padding:[32,32,32,32],duration:200})}><Maximize size={16}/></Button><Button size="icon" variant="secondary" aria-label={t('Export map package')} tooltip={t('Export map package')} disabled={busy} onClick={save}><Download size={16}/></Button></div><p className="vector-source-note">{t('Rendered map image. Display colors are not calibrated measurements. Transparent pixels may indicate areas without imagery.')}</p><Disclosure summary={t('Map source details')}><MapSourceDetails asset={asset}/></Disclosure></>}{error&&<p className="vector-error" role="alert">{t(error)}</p>}</aside></ResizablePanel><ResizeHandle label={t('Resize map image details')}/><ResizablePanel id="map-image-map" minSize="360px"><div className="vector-map" ref={target}/>{!data&&!error&&<div className="vector-map-state" role="status"><Spinner/>{t('Opening saved map image')}</div>}{asset&&<div className="wms-map-attribution">{asset.source.attribution||asset.source.serviceTitle}</div>}</ResizablePanel></ResizableGroup></main>;
}
