import test from 'node:test';import assert from 'node:assert/strict';
import {xyzMatrix,xyzPlan,xyzTileUrl,validateXyzConfiguration,validateXyzService,validateXyzImage,defaultTileConfig} from './xyz-client.js';
import {validateMapService,validateMapImage} from './wms-client.js';
import {mapProtocol} from './arcgis-map-client.js';
const id='735f227b-5f95-473f-967b-077f3419bc68',sha='a'.repeat(64),c={scheme:'TMS',urlTemplate:'https://example.com/tiles/{z}/{x}/{y}.png',grid:defaultTileConfig()};
function service(){const url=new URL(c.urlTemplate).href;return {id,name:'Test',title:'Test',url,mapUrl:url,version:'xyz-1',capabilitiesSha256:sha,connectedAt:'2026-10-03T00:00:00Z',maxWidth:2048,maxHeight:2048,accessConstraints:'',xyz:structuredClone(c),layers:[{name:'tiles',title:'Test',crs:'EPSG:3857',styles:[],bounds:null,time:null,attribution:null}]};}
function image(){const p=xyzPlan([-2,-2,2,2],c,6),s=service(),tiles=p.tiles.map(t=>({...t,bytes:123,sha256:sha,requestUrl:xyzTileUrl(c,6,t.row,t.col)}));return{id,name:'Test · TMS',width:p.width,height:p.height,bytes:500,sha256:sha,bounds:p.bounds,imageExtent:p.extent,crs:'EPSG:3857',source:{serviceName:'Test',serviceTitle:'Test',serviceUrl:s.url,mapEndpoint:s.url,version:s.version,layerName:'tiles',layerTitle:'Test',style:'',time:null,requestCrs:'EPSG:3857',capabilitiesSha256:sha,requestedAt:s.connectedAt,requestUrl:tiles[0].requestUrl,accessConstraints:'',attribution:null,selection:'pixel-window-rendered-tiles',xyz:{configuration:structuredClone(c),logicalZoom:6,matrixSet:'WebMercator',matrix:xyzMatrix(c,6),requestedBounds:[-2,-2,2,2],pixelWindow:p.window,tiles,archiveBytes:500,archiveSha256:sha}}};}
test('XYZ/TMS request rows and URL offset use the same global pixel model',()=>{const g={...c,grid:{...c.grid,tileSize:512,minZoom:1,zoomOffset:-1}};assert.equal(xyzTileUrl(g,3,1,2),'https://example.com/tiles/2/2/6.png');assert.equal(xyzTileUrl({...g,scheme:'XYZ'},3,1,2),'https://example.com/tiles/2/2/1.png');assert.equal(xyzMatrix(g,3).matrixWidth,8);assert.equal(xyzMatrix(c,3).scaleDenominator,xyzMatrix(g,3).scaleDenominator*2);assert.throws(()=>xyzTileUrl(g,3,8,2));assert.throws(()=>xyzPlan([-10,86,10,89],g,3));});
test('validates configured services and rejects malformed URLs or unsupported grids',()=>{assert.equal(validateMapService(service()).xyz.scheme,'TMS');assert.equal(mapProtocol(service()),'TMS');for(const url of ['http://example.com/{z}/{x}/{y}.png','https://localhost/{z}/{x}/{y}.png','https://example.com/{z}/{x}/{y}.png?key=abc','https://{z}.example.com/{x}/{y}.png','https://example.com/{z}/{x}/{y}/{s}','https://example.com/../{z}/{x}/{y}.png','https://tile.openstreetmap.org/{z}/{x}/{y}.png'])assert.throws(()=>validateXyzConfiguration({...c,urlTemplate:url}),url);for(const edit of [s=>s.xyz.grid.tileSize=128,s=>s.xyz.grid.minZoom=20,s=>s.xyz.grid.zoomOffset=-1,s=>s.wmts={},s=>s.layers[0].time={values:'2025-06-27'}]){const s=service();edit(s);assert.throws(()=>validateMapService(s));}assert.equal(validateXyzService(service()).id,id);});
test('saved image checks every logical row, actual URL, native extent and archive',()=>{assert.equal(validateMapImage(image()).id,id);assert.equal(mapProtocol(image().source),'TMS');for(const edit of [a=>a.source.xyz.tiles.reverse(),a=>a.source.xyz.tiles[0].requestUrl+='?changed=1',a=>a.source.xyz.configuration.scheme='XYZ',a=>a.imageExtent[0]+=1,a=>a.source.xyz.logicalZoom=5,a=>a.source.xyz.matrix.tileWidth=512,a=>a.source.xyz.matrixSet='regional',a=>a.source.time='2025-06-27',a=>a.source.xyz.archiveBytes=0,a=>a.source.arcgis={}]){const a=image();edit(a);assert.throws(()=>validateMapImage(a));}assert.equal(validateXyzImage(image()).id,id);});
test('official encoded layer names preserve exact bottom-origin request paths',()=>{
 const url='https://tiles.geoservice.dlr.de/service/tms/1.0.0/eoc%3Abasemap@EPSG%3A3857@png/{z}/{x}/{y}.png';
 assert.equal(xyzTileUrl({...c,urlTemplate:url},6,21,34),'https://tiles.geoservice.dlr.de/service/tms/1.0.0/eoc%3Abasemap@EPSG%3A3857@png/6/34/42.png');
 assert.equal(xyzTileUrl({...c,urlTemplate:'https://example.com/caf%C3%A9/{z}/{x}/{y}.png'},6,21,34),'https://example.com/caf%C3%A9/6/34/42.png');
});
test('encoded separators, traversal, control characters and extra decoding layers are rejected',()=>{
 for(const segment of ['%2f','%5C','%25','%3F','%23','%7Bz%7D','%00','%0d','%C2%85','%2e','.%2E','%252e%252e','%FF','%C0%AF','%','%2','%2G']){
  assert.throws(()=>validateXyzConfiguration({...c,urlTemplate:`https://example.com/${segment}/{z}/{x}/{y}.png`}),segment);
 }
});
