import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {createServer} from 'node:http';
import {mkdtemp,mkdir,readFile,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {documentId,documentInput,readDocument,sessionDocuments,validDocument} from './document-store.mjs';
import {startBridge,BRIDGE_MODEL} from './protocol.mjs';
import {openaiResponsesReply} from '../scripts/acceptance/openai-responses-wire.mjs';

// This owned two-page PDF was generated by the native lopdf ingestion check.
// The test uses the installed SDK and a loopback upstream, never a live model.
const bytes=await readFile(new URL('./fixtures/two-pages.pdf',import.meta.url));
const document={id:'de0fce45e11dd2979794743f0dcd157b1d69a2ccb35baf63899e8f21344751f1',name:'sample.pdf',mimeType:'application/pdf',bytes:bytes.length,characters:0,pages:2};
const definitions=[{name:'geod_projects_list',description:'Read saved projects',inputSchema:{type:'object',properties:{},additionalProperties:false}}];

test('PDF original bytes survive SDK transmission, context recovery and bridge restart without crossing sessions',async t=>{
  const home=await mkdtemp(join(tmpdir(),'geod-pdf-wire-'));t.after(()=>rm(home,{recursive:true,force:true}));
  await mkdir(join(home,'documents'));
  await writeFile(join(home,'documents',`${document.id}.pdf`),bytes);
  await writeFile(join(home,'documents',`${document.id}.json`),JSON.stringify({version:1,document}));
  assert.equal(documentId(bytes,document),document.id);
  assert.deepEqual((await readDocument(home,document.id)).bytes,bytes);
  assert(!documentInput({document}).includes(bytes.toString('base64')));
  assert.notEqual(createHash('sha256').update(bytes).digest('hex'),document.id);
  const sessionId=randomUUID(),seen=[],key='owned-pdf-synthetic-key';let wireFailure;
  const server=createServer(async(request,response)=>{
    try{
      const chunks=[];for await(const part of request)chunks.push(part);
      const body=JSON.parse(Buffer.concat(chunks));seen.push(body);
      assert.equal(request.url,'/v1/responses');assert.equal(request.headers.authorization,'Bearer '+key);
      assert.equal(body.store,false);
      const files=body.input.flatMap(item=>Array.isArray(item.content)?item.content:[]).filter(part=>part.type==='input_file');
      if(seen.length===4)assert.equal(files.length,0);
      else{
        assert.equal(files.length,1);assert.equal(files[0].filename,document.name);
        assert.equal(files[0].file_data,'data:application/pdf;base64,'+bytes.toString('base64'));
        assert.deepEqual(Buffer.from(files[0].file_data.split(',')[1],'base64'),bytes);
      }
      if(seen.length===2){assert(body.input.some(item=>item.type==='function_call' && item.call_id==='read'));
        assert(body.input.some(item=>item.type==='function_call_output' && item.call_id==='read'));}
      openaiResponsesReply(response,{model:body.model,callId:seen.length===1?'read':undefined,text:'Controlled PDF transport check'});
    }catch(error){wireFailure=error;response.writeHead(500).end('{"error":{"message":"Controlled PDF wire assertion failed"}}');}
  });
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  t.after(()=>new Promise(resolve=>{server.closeAllConnections();server.close(resolve);}));
  const config={label:'Controlled PDF wire',protocol:'openai-responses',baseUrl:`http://127.0.0.1:${server.address().port}/v1`,model:'controlled-pdf',apiKey:key};
  const open=()=>startBridge({config,definitions,home,identity:'owned-pdf-wire',sessionId,token:'owned-pdf-loopback',documentContext:id=>id===sessionId?[document]:[]});
  let bridge=await open();t.after(()=>bridge.close());
  let output;
  const post=async input=>{const response=await fetch(bridge.baseUrl+'/responses',{method:'POST',headers:{authorization:'Bearer owned-pdf-loopback'},body:JSON.stringify({model:BRIDGE_MODEL,stream:true,input})});
    const text=await response.text();if(response.status===200){assert(text.includes('response.completed'));
      output=text.split('\n').filter(line=>line.startsWith('data: ')).map(line=>JSON.parse(line.slice(6))).find(event=>event.type==='response.completed').response.output;}
    return response.status;};
  assert.equal(await post([{role:'user',content:documentInput({document})}]),200);
  await bridge.resetBudget(sessionId);
  assert.equal(await post([{role:'user',content:'Compacted working summary'},...output.map(({id,...item})=>item),
    {type:'function_call_output',call_id:'read',output:'{"total":0}'}]),200);
  await bridge.close();bridge=await open();
  assert.equal(await post([{role:'user',content:'Continue the saved conversation'}]),200);
  await bridge.resetBudget(randomUUID());assert.equal(await post([{role:'user',content:'A different active conversation'}]),200);
  await bridge.resetBudget(sessionId);await writeFile(join(home,'documents',`${document.id}.pdf`),Buffer.alloc(bytes.length,120));
  assert.equal(await post([{role:'user',content:'Changed bytes must be refused'}]),400);
  assert.equal(seen.length,4);assert(!wireFailure,wireFailure?.message);
});

test('PDF metadata and session byte limits distinguish PDF from text and refuse oversized mixed attachments',()=>{
  assert(validDocument(document));
  for(const changed of [{...document,pages:0},{...document,pages:21},{...document,pages:undefined},{...document,characters:1},{...document,bytes:2*1024*1024+1},{...document,name:'data.txt'}])assert(!validDocument(changed));
  assert.notEqual(documentId(bytes,{...document,pages:3}),document.id);
  const files=Array.from({length:5},(_,index)=>({...document,id:String(index).repeat(64),bytes:2*1024*1024}));
  const entries=values=>Array.from({length:Math.ceil(values.length/3)},(_,index)=>({type:'user',documents:values.slice(index*3,index*3+3)}));
  assert.equal(sessionDocuments(entries(files.slice(0,4))).length,4);assert.throws(()=>sessionDocuments(entries(files)));
  const mixed=[...entries(files.slice(0,4)),{type:'user',images:Array.from({length:3},(_,index)=>({id:'image-'+index,bytes:5*1024*1024}))}];
  assert.throws(()=>sessionDocuments(mixed));
});
